sudo: required
services:
  - docker

before_install:
  - docker build -t raulcontrerasrubio/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true raulcontrerasrubio/react-test npm run test

after_success:
  - docker build -t raulcontrerasrubio/fibonacci-client ./client
  - docker build -t raulcontrerasrubio/fibonacci-nginx ./nginx
  - docker build -t raulcontrerasrubio/fibonacci-server ./server
  - docker build -t raulcontrerasrubio/fibonacci-worker ./worker
  # Log in to the docker CLI with Travis CI environment variables
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push to docker hub
  - docker push raulcontrerasrubio/fibonacci-client
  - docker push raulcontrerasrubio/fibonacci-nginx
  - docker push raulcontrerasrubio/fibonacci-server
  - docker push raulcontrerasrubio/fibonacci-worker

# Create a new IAM which is only capable of deploy an EB app
deploy:
  # edge: true # If it were a persistent error of missing bucket_name
  provider: elasticbeanstalk
  region: us-west-2
  app: "fibonacci-app"
  env: "FibApp-env"
  bucket_name: "name of the bucket"
  bucket_path: "path of the bucket"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
